name: foodlans_driver
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

# font_awesome_flutter: ^9.1.0
#   country_code_picker: ^2.0.2
#   flutter_svg: ^0.22.0
#   timeline_tile: ^2.0.0
#   flutter_rating_bar: ^4.0.0
#   retrofit: any
#   shared_preferences: ^2.0.6
#   json_annotation: ^4.0.1
#   modal_progress_hud: 
#   fluttertoast: ^8.0.7
#   google_maps_flutter: ^2.0.6
#   flutter_polyline_points: ^1.0.0
#   location: ^4.3.0
#   cached_network_image: ^3.0.0
#   flutter_spinkit: ^5.0.0
#   intl: ^0.17.0
#   url_launcher: ^6.0.7
#   onesignal_flutter: ^3.0.0



  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^9.1.0
  country_code_picker: ^1.6.2
  flutter_svg: ^0.19.0
  timeline_tile: ^1.0.0
  flutter_rating_bar: ^3.2.0+1
  retrofit: any
  shared_preferences: ^0.5.12
  modal_progress_hud: ^0.1.3
  fluttertoast: ^7.1.1
  google_maps_flutter: ^1.2.0
  flutter_polyline_points: ^0.2.4
  location: ^3.0.0
  cached_network_image: ^2.5.0
  flutter_spinkit: ^4.1.2
  intl: ^0.17.0
  url_launcher: ^5.7.8
  easy_localization: ^2.3.3+1

  onesignal_flutter: ^2.6.1






dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^1.4.0+2
  build_runner: ^1.10.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: PoppinsSemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf

    - family: PoppinsBlack
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf

    - family: PoppinsBlackItalic
      fonts:
        - asset: assets/fonts/Poppins-BlackItalic.ttf

    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: PoppinsBoldItalic
      fonts:
        - asset: assets/fonts/Poppins-BoldItalic.ttf

    - family: PoppinsExtraBold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf

    - family: PoppinsExtraBoldItalic
      fonts:
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf

    - family: PoppinsExtraLight
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf

    - family: PoppinsExtraLightItalic
      fonts:
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf

    - family: PoppinsItalic
      fonts:
        - asset: assets/fonts/Poppins-Italic.ttf

    - family: PoppinsLight
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

    - family: PoppinsLightItalic
      fonts:
        - asset: assets/fonts/Poppins-LightItalic.ttf

    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: PoppinsMediumItalic
      fonts:
        - asset: assets/fonts/Poppins-MediumItalic.ttf

    - family: PoppinsSemiBoldItalic
      fonts:
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf

    - family: PoppinsThin
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf

    - family: PoppinsThinItalic
      fonts:
        - asset: assets/fonts/Poppins-ThinItalic.ttf



  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
