// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>> load(String fullPath, Locale locale ) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> ar = {
  "address": "العنوان",
  "select_address": "اختار العنوان",
  "Food": "طعام",
  "Grocery": "خضروات",
  "Search": "ابحث عن مطاعم وأطباق ...",
  "FILTERS": "فلترة",
  "RESTAURANTS": "مطاعم",
  "top_rated": "أعلى التقييمات",
  "open_new": "جديد",
  "Nearest_Me": "الأقرب إلي",
  "Most_Popular": "الأكثر شعبية",
  "Cost_High_to_low": "التكلفة العالية إلى المنخفضة",
  "Cost_low_to_High ": "التكلفة المنخفضة إلى العالية",
  "Newly_Launched": "اطلق حديثا",
  "Pocket_Friendly": "بحجم الجيب",
  "Express_Delivery": "تسليم سريع",
  "Offers_near_you": "عروض بالقرب منك",
  "Only_on_Foodlines": "فقط على خطوط الطعام",
  "Popular_This_Week": "الشائع لهذا الأسبوع",
  "Search_for_Shop": "البحث عن متجر ، فئة ، رمز سري ...",
  "Trending_Near_You": "تتجه بالقرب منك",
  "View_More": "عرض المزيد",
  "Store": "متجر",
  "New": "جديد",
  "current_distanceInMeters": "المسافة الحالية بالمتر",
  "current_distanceinkm": "المسافة الحالية بالكيلومتر",
  "No_Data": "لايوجد بيانات",
  "Internal_Server_Error": "خطأ في الخادم الداخلي",
  "Categories": "فئات",
  "No_Data_Avaialable": "لا تتوافر بيانات",
  "No_Data_Avaialable_space": "لا تتوافر /nالبيانات",
  "Search_for_Category": "بحث عن فئة ...",
  "Home": "الرئيسية",
  "Notification": "الإشعارات",
  "Payment_Method": "طريقة الدفع او السداد",
  "Promo_Code": "رمز ترويجي",
  "Invite_Friends": "دعوة الأصدقاء",
  "Order_History": "تاريخ الطلب",
  "Help_Center": "مركز المساعدة",
  "Setting": "الإعدادت",
  "Logout": "تسجيل الخروج",
  "Address_Not_Available": "العنوان غير متوفر",
  "Guest_User": "حساب زائر",
  "Notifcation": "الإشعارات",
  "APPLY": "تطبيق",
  "CONTINUE": "متابعة",
  "ONLINE_PAY": "الدفع عبر الإنترنت",
  "CASH": "كاش",
  "amount": "كمية",
  "name": "الإسم",
  "description": "الوصف",
  "Payment": "دفع",
  "prefill": "التعبئة قبل",
  "contact": "اتصل",
  "email": "الإيميل",
  "external": "خارجي",
  "wallets": "محافظ",
  "CONGRATULATIONS": "تهانينا",
  "Your_Payment_Successfully_Received": "تم استلام دفعتك بنجاح",
  "THANK_YOU": "شكراً لك",
  "Order_booked_successfully": "تم حجز الطلب بنجاح",
  "Errow_while_place_order": "خطأ أثناء تقديم الطلب.",
  "INVITE_YOUR_FRIENDS": "دعوة الأصدقاء",
  "When_your_friend": "عندما يقوم صديقك بتثبيت التطبيق برمز الإحالة الخاص بك \\n واكتمال طلب واحد ، ستطلب كلاكما طلبًا واحدًا مجانًا.",
  "Referral_Code": "كود التحويل",
  "Current_Order": "الترتيب الحالي",
  "ITEMS": "العناصر",
  "ORDERED_ON": "تم طلبه في",
  "TOTAL_AMOUNT": "المبلغ الإجمالي",
  "Cancel_Order": "الغاء الطلب",
  "No_Data_Available": "لا تتوافر بيانات",
  "Post_Order": "طلب آخر",
  "Do_you_want_to_cancel_this_order": "هل تريد إلغاء هذا الطلب؟",
  "No_Go_Back": "لا ، رجوع",
  "Yes_Cancel_It": "نعم ، قم بإلغائها",
  "Repeat_Order": "إعادة الطلب",
  "No_Review_available": "لا توجد مراجعة متاحة.",
  "days_ago": "2 منذ أيام",
  "Enter_Your_Name": "أدخل أسمك",
  "Enter_Your_Email": "أدخل بريدك الإلكتروني",
  "Phone_Number": "رقم الهاتف",
  "Enter_Your_Phone_Number": "أدخل رقم هاتفك",
  "Enter_Your_Location": "أدخل موقعك",
  "Edit_Profile": "تعديل الملف الشخصي",
  "Call": "يتصل",
  "Default_Address": "العنوان الافتراضي",
  "Change": "تغيير",
  "language": "اللغة",
  "arabic": "عربي",
  "english": "الانجليزي",
  "Profile_data_updated_successfully": "تم تحديث بيانات الملف الشخصي بنجاح",
  "Email_is_Required": "البريد الالكتروني مطلوب",
  "Enter_Valid_Email": "أدخل بريد إلكتروني صالح",
  "Location_is_Required": "الموقع مطلوب",
  "Please_enter_mobile_number": "الرجاء إدخال رقم الهاتف المحمول",
  "Please_enter_valid_mobile_number": "الرجاء إدخال رقم هاتف محمول صحيح",
  "Name_is_Required": "مطلوب الاسم",
  "Enter_Valid_Name": "أدخل اسمًا صالحًا",
  "phone": "موبايل",
  "Location": "الموقع",
  "No_Photo_available": "لا توجد صور متاحة",
  "Edit": "تعديل",
  "Reviews": "التقييمات",
  "Photo": "صورة",
  "Loading": "تحميل...",
  "SIGN_IN": "تسجيل الدخول",
  "Email": "البريد الإلكتروني",
  "Please_wait": "الرجاء الإنتظار",
  "Name": "الإسم",
  "Password": "كلمة السر",
  "Enter_Your_Password": "أكتب كلمة السر",
  "Confirm_Password": "تأكيد كلمة المرور",
  "Enter_Your_Confirm_Password": "أدخل تأكيد كلمة المرور الخاصة بك",
  "SIGN_UP": "اشتراك",
  "OR": "أو",
  "Already_have_an_account": "هل لديك حساب؟",
  "Sign_in": "تسجيل الدخول",
  "Password_is_Required": "كلمة المرور مطلوبة",
  "Password_required": "كلمة المرور المطلوبة: الأبجدية والرقم و 8 أحرف",
  "Password_and_Confirm_Password_does_not_match": "كلمة المرور وتأكيد كلمة المرور غير متطابقين.",
  "Password_required_Alphabet": "كلمة المرور المطلوبة: الأبجدية والرقم و 8 أحرف",
  "Signup": "إشتراك",
  "If_you_are_new_user": "إذا كنت مستخدم جديد؟",
  "Forgot_Password": "هل نسيت كلمة المرور؟",
  "Earnings": "أرباح",
  "Review": "تقييم",
  "Profile": "الصفحة الشخصية",
  "Order_Request": "طلب",
  "Grocery_Request": "طلب بقالة",
  "Empty": "فارغ",
  "Today_Trip": "رحلة  اليوم",
  "Trips": "رحلات",
  "Cancel_Trips": "إلغاء الرحلات",
  "Press_again_to_exit": "اضغط مرة أخرى للخروج",
  "canceled": "ألغيت",
  "collected": "جمعت",
  "trip": "رحلة",
  "Youre_offline_now": "أنت غير متصل الآن",
  "Youre_online_now": "أنت متصل الآن",
  "EARNING_HISTORY": " تاريخ الكسب",
  "No_Earning": "لا أرباح",
  "Select_Ending_Earning_date": "حدد تاريخ الانتهاء",
  "Not_now": "ليس الان",
  "Select": "اختار",
  "Enter_valid_date": "أدخل تاريخًا صالحًا",
  "Enter_date_in_valid_range": "أدخل التاريخ في نطاق صالح",
  "Error_white_getting_Order_Details": "خطأ في الحصول على تفاصيل الطلب",
  "Order_Rejected_Successfully": "تم رفض الطلب بنجاح",
  "ORDER_DETAIL": "تفاصيل الطلب",
  "Something_went_wrong": "هناك خطأ ما",
  "Bill_Details": "تفاصيل الفاتورة",
  "Item_Total": "مجموع الاشياء",
  "Restaurant_Charges": "رسوم المطعم",
  "Total_Discount": "إجمالي الخصم",
  "Delivery_Fee": "رسوم التوصيل",
  "Cancellation_Fee": "رسوم الإلغاء",
  "To_Pay": "للدفع",
  "ACCEPTED": "قبول",
  "Reject": "رفض",
  "order_id_is": "معرف الطلب هو",
  "Select_Start_Earning_date": "حدد تاريخ بدء الكسب",
  "GROCERY_ORDER_REQUEST": "طلب بقالة",
  "Order_Id_No": "رقم معرف الطلب",
  "Pickup_Address": "عنوان الاستلام",
  "Delivery_Address": "عنوان التسليم",
  "origin": "الأصل",
  "destination": "وجهة",
  "origin_latitude_is": "خط العرض الأصل هو",
  "PAYMENT_COLLECTED": "تم تحصيل المدفوعات",
  "Why_do_you_cancel_your_order": "لماذا تلغي طلبك؟",
  "Delivery_is_delay_for_heavy_rain": "تسليم سريع",
  "Customer_cancel_order": "يقوم العميل بإلغاء الطلب",
  "VIEW_ORDER": "مشاهدة الطلب",
  "CANCEL_ORDER": "الغاء الطلب",
  "Your_order": "طلبك",
  "Order_Confirmed": "تم تاكيد الطلب",
  "On_the_way_to_pickup_your_food": "في الطريق لجلب طعامك",
  "Food_is_collected": "يتم جمع الطعام",
  "Food_is_On_the_way": "الطعام على الطريق",
  "Reach_at_door_step": "الطلب عند عتبة الباب",
  "Delivered": "تم التوصيل",
  "Your_order_is_delivered": "تم تسليم طلبك ، تم تحصيل مدفوعاتك",
  "Please_enter_some_text": "الرجاء إدخال نص",
  "Enter_more_than_6_character": "أدخل على الأقل 6 حروف",
  "Password_is_empty": "لا يوجد كلمة سر",
  "Confirm_Password_Does_Not_Match": "تأكيد كلمة المرور غير متطابق",
  "REVIEW": "تقييمات",
  "there_are_no_reviews_yet": "لا يوجد تقييمات...",
  "SAVE": "حفظ",
  "New_Password": "كلمة سر جديدة",
  "Change_Password": "تغيير كلمة السر",
  "FOOD_ORDER_REQUEST": "طلب طعام"
};
static const Map<String,dynamic> en = {
  "address": "Adress",
  "select_address": "Select Address",
  "Food": "Food",
  "Grocery": "Grocery",
  "Search": "Search for Restaurants and dishes...",
  "FILTERS": "FILTERS",
  "RESTAURANTS": "RESTAURANTS",
  "top_rated": "Top Rated",
  "open_new": "Open New",
  "Nearest_Me": "Nearest Me",
  "Most_Popular": "Most Popular",
  "Cost_High_to_low": "Cost High to low",
  "Cost_low_to_High ": "Cost low to High ",
  "Newly_Launched": "Newly Launched",
  "Pocket_Friendly": "Pocket Friendly",
  "Express_Delivery": "Express Delivery",
  "Offers_near_you": "Offers near you",
  "Only_on_Foodlines": "Only on Foodlines",
  "Popular_This_Week": "Popular This Week",
  "Search_for_Shop": "Search for Shop, Category, Pincode...",
  "Trending_Near_You": "Trending Near You",
  "View_More": "View More",
  "Store": "Store",
  "New": "New",
  "current_distanceInMeters": "current distance In Meters",
  "current_distanceinkm": "current distance in km",
  "No_Data": "No Data",
  "Internal_Server_Error": "Internal Server Error",
  "Categories": "Categories",
  "No_Data_Avaialable": "No Data Avaialable",
  "No_Data_Avaialable_space": "No Data/n Avaialable",
  "Search_for_Category": "Search for Category...",
  "Home": "Home",
  "Notification": "Notification",
  "Payment_Method": "Payment Method",
  "Promo_Code": "Promo Code",
  "Invite_Friends": "Invite Friends",
  "Order_History": "Order History",
  "Help_Center": "Help Center",
  "Setting": "Setting",
  "Logout": "Logout",
  "Address_Not_Available": "Address Not Available",
  "Guest_User": "Guest User",
  "Notifcation": "NOTIFICATION",
  "APPLY": "APPLY",
  "CONTINUE": "CONTINUE",
  "ONLINE_PAY": "ONLINE PAY",
  "CASH": "CASH",
  "amount": "amount",
  "name": "name",
  "description": "description",
  "Payment": "Payment",
  "prefill": "prefill",
  "contact": "contact",
  "email": "email",
  "external": "external",
  "wallets": "wallets",
  "CONGRATULATIONS": "CONGRATULATIONS",
  "Your_Payment_Successfully_Received": "Your Payment Successfully Received",
  "THANK_YOU": "THANK YOU",
  "Order_booked_successfully": "Order booked successfully",
  "Errow_while_place_order": "Errow while place order.",
  "INVITE_YOUR_FRIENDS": "INVITE YOUR FRIENDS",
  "When_your_friend": "When your friend install app with your referral code\\n and one order complete, you will both one order free.",
  "Referral_Code": "Referral Code",
  "Current_Order": "Current Order",
  "ITEMS": "ITEMS",
  "ORDERED_ON": "ORDERED ON",
  "TOTAL_AMOUNT": "TOTAL AMOUNT",
  "Cancel_Order": "Cancel Order",
  "No_Data_Available": "No Data Available",
  "Post_Order": "Post Order",
  "Do_you_want_to_cancel_this_order": "Do you want to cancel this order?",
  "No_Go_Back": "No, Go Back",
  "Yes_Cancel_It": "Yes, Cancel It",
  "Repeat_Order": "Repeat Order",
  "No_Review_available": "No Review available.",
  "days_ago": "2 days ago",
  "Enter_Your_Name": "Enter Your Name",
  "Enter_Your_Email": "Enter Your Email",
  "Phone_Number": "Phone Number",
  "Enter_Your_Phone_Number": "Enter Your Phone Number",
  "Enter_Your_Location": "Enter Your Location",
  "Edit_Profile": "Edit Profile",
  "Call": "Call",
  "Default_Address": "Default Address",
  "Change": "Change",
  "language": "language",
  "arabic": "arabic",
  "english": "english",
  "Profile_data_updated_successfully": "Profile data updated successfully",
  "Email_is_Required": "Email is Required",
  "Enter_Valid_Email": "Enter Valid Email",
  "Location_is_Required": "Location is Required",
  "Please_enter_mobile_number": "Please enter mobile number",
  "Please_enter_valid_mobile_number": "Please enter valid mobile number",
  "Name_is_Required": "Name is Required",
  "Enter_Valid_Name": "Enter Valid Name",
  "phone": "phone",
  "Location": "Location",
  "No_Photo_available": "No Photo Available",
  "Edit": "Edit",
  "Reviews": "Reviews",
  "Photo": "Photo",
  "Loading": "Loading...",
  "SIGN_IN": "SIGN IN",
  "Email": "Email",
  "Please_wait": "Please wait",
  "Name": "Name",
  "Password": "Password",
  "Enter_Your_Password": "Enter Your Password",
  "Confirm_Password": "Confirm Password",
  "Enter_Your_Confirm_Password": "Enter Your Confirm Password",
  "SIGN_UP": "SIGN UP",
  "OR": "OR",
  "Already_have_an_account": "Already have an account?",
  "Sign_in": "Sign in",
  "Password_is_Required": "Password is Required",
  "Password_required": "Password required: Alphabet, Number & 8 chars",
  "Password_and_Confirm_Password_does_not_match": "Password and Confirm Password does not match.",
  "Password_required_Alphabet": "Password required: Alphabet, Number & 8 chars",
  "Signup": "Signup",
  "If_you_are_new_user": "If you are new user?",
  "Forgot_Password": "Forgot Password?",
  "Earnings": "Earnings",
  "Review": "Review",
  "Profile": "Profile",
  "Order_Request": "Order Request",
  "Grocery_Request": "Grocery Request",
  "Empty": "Empty",
  "Today_Trip": "Today\\'s Trip",
  "Trips": "Trips",
  "Cancel_Trips": "Cancel Trips",
  "Press_again_to_exit": "Press again to exit",
  "canceled": "canceled",
  "collected": "collected",
  "trip": "trip",
  "Youre_offline_now": "You\\'re offline now",
  "Youre_online_now": "You\\'re online now",
  "EARNING_HISTORY": "EARNING HISTORY",
  "No_Earning": "No Earning",
  "Select_Ending_Earning_date": "Select Ending Earning date",
  "Not_now": "Not now",
  "Select": "Select",
  "Enter_valid_date": "Enter valid date",
  "Enter_date_in_valid_range": "Enter date in valid range",
  "Error_white_getting_Order_Details": "Error white getting Order Details",
  "Order_Rejected_Successfully": "Order Rejected Successfully",
  "ORDER_DETAIL": "ORDER DETAIL",
  "Something_went_wrong": "Something went wrong",
  "Bill_Details": "Bill Details",
  "Item_Total": "Item Total",
  "Restaurant_Charges": "Restaurant Charges",
  "Total_Discount": "Total Discount",
  "Delivery_Fee": "Delivery Fee",
  "Cancellation_Fee": "Cancellation Fee",
  "To_Pay": "To Pay",
  "ACCEPTED": "ACCEPTED",
  "Reject": "Reject",
  "order_id_is": "order id is",
  "Select_Start_Earning_date": "Select Start Earning date",
  "GROCERY_ORDER_REQUEST": "GROCERY ORDER REQUEST",
  "Order_Id_No": "Order Id No",
  "Pickup_Address": "Pickup Address",
  "Delivery_Address": "Delivery Address",
  "origin": "origin",
  "destination": "destination",
  "origin_latitude_is": "origin latitude is",
  "PAYMENT_COLLECTED": "PAYMENT COLLECTED",
  "Why_do_you_cancel_your_order": "Why do you cancel your order?",
  "Delivery_is_delay_for_heavy_rain": "Delivery is delay for heavy rain",
  "Customer_cancel_order": "Customer cancel order.",
  "VIEW_ORDER": "VIEW ORDER",
  "CANCEL_ORDER": "CANCEL ORDER",
  "Your_order": "Your order",
  "Order_Confirmed": "Order Confirmed",
  "On_the_way_to_pickup_your_food": "On the way to pickup your food",
  "Food_is_collected": "Food is collected",
  "Food_is_On_the_way": "Food is On the way",
  "Reach_at_door_step": "Reach at door step",
  "Delivered": "Delivered",
  "Your_order_is_delivered": "Your order is delivered\\nyour payment has been collected",
  "Please_enter_some_text": "Please enter some text",
  "Enter_more_than_6_character": "Enter more than 6 character",
  "Password_is_empty": "Password is empty",
  "Confirm_Password_Does_Not_Match": "Confirm Password Does Not Match",
  "REVIEW": "REVIEW",
  "there_are_no_reviews_yet": "there are no reviews yet...",
  "SAVE": "SAVE",
  "New_Password": "New Password",
  "Change_Password": "Change Password",
  "FOOD_ORDER_REQUEST": "FOOD ORDER REQUEST"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"ar": ar, "en": en};
}
